// Plays a catalog karaoke video on the projector and screenshots the singer's view.
import { chromium } from 'playwright';
import { resolve } from 'node:path';
const [,, device = 'ipad', query = 'Labios'] = process.argv;
const presets = { ipad: { viewport: { width: 1180, height: 820 } }, iphone: { viewport: { width: 844, height: 390 } }, 'iphone-port': { viewport: { width: 390, height: 844 } } };
const wav = resolve('.cache/vox/test_voice.wav');
const browser = await chromium.launch({ headless: true, args: ['--use-angle=d3d11', '--autoplay-policy=no-user-gesture-required', '--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', `--use-file-for-fake-audio-capture=${wav}`] });
const ctx = await browser.newContext({ ...presets[device], deviceScaleFactor: 1, isMobile: true, hasTouch: true, permissions: ['microphone'] });
await ctx.addInitScript(() => localStorage.setItem('baqueta:settings:v1', JSON.stringify({ tourSeen: true, tipSeen: true })));
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://localhost:5173/');
await page.waitForSelector('#start:not([hidden])', { timeout: 180000 });
await page.tap('#start');
await page.waitForTimeout(300);
await page.tap('[data-station="mic"]');
await page.waitForTimeout(1500);
await page.tap('#mic-btn');
await page.waitForTimeout(300);
await page.tap('[data-hp="1"]');
await page.waitForTimeout(800);
await page.tap('#mic-songs');
await page.waitForTimeout(400);
await page.screenshot({ path: `.cache/shots/yt-list-${device}.png` });
await page.fill('#song-search', query);
await page.waitForTimeout(300);
await page.tap('#song-results [data-video]');
await page.waitForTimeout(9000);
const st = await page.evaluate(() => ({ state: window.app.mic.video.state, visible: window.app.mic.video.visible, key: window.app.mic.detectedKey }));
console.log(JSON.stringify(st));
await page.screenshot({ path: `.cache/shots/yt-play-${device}.png` });
console.log('errors', errors);
await browser.close();
